# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

require_relative '../node_modules/react-native-permissions/scripts/setup'
setup_permissions([
  'Camera'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AgriMRV' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Enable Hermes dSYM generation and fix build settings
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['ENABLE_BITCODE'] = 'NO'
    #     config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        
    #     # Specific settings for Hermes
    #     if target.name == 'hermes-engine'
    #       config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
    #       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #     end
        
    #     # Ensure proper architecture support
    #     config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
    #     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    #   end
    # end
    
    # # Fix for Xcode 15+ compatibility
    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    # end
  end
end
